export enum ApplicationStatus {
  DRAFT = `DRAFT`,
  SUBMITTED = `SUBMITTED`,
  UNDER_REVIEW = `UNDER_REVIEW`,
  PENDING_CLARIFICATION = `PENDING_CLARIFICATION`,
  FINAL_REVIEW = `FINAL_REVIEW`,
  APPROVED = `APPROVED`,
  REJECTED = `REJECTED`,
}
